name: CI

on:
  push:
    branches:
    - landing-page
  pull_request:
    branches:
    - landing-page

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Parse
      id: parser
      run: |
        $output = '${{ steps.block.outputs.output }}' | ConvertFrom-Json
        Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"
      shell: pwsh

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '23.x'

    - name: Build
      run: |
        npm install
      env:
        G_NPM: ${{ secrets.G_NPM2 }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm --version
   #- run: npm ci

   # - name: Build
    #  run: |
      #  $output = '${{ steps.block.outputs.output }}' | ConvertFrom-Json
      #  ($env:REACT_APP_BLOCK = "$($output.data.result)") -and (npm run build)
     # shell: pwsh

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
      env:
        TWITTER_API_KEYY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRETT: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKENN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRETT: ${{ secrets.TWITTER_ACCESS_SECRET }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version

    #- name: Install Git
    # run: sudo apt-get install -y git
    
    - name: Install Volara
      run: |
        git clone https://github.com/volaradlp/minercli.git
        cd minercli
        source setup.sh
        volara --version
        
      
        
        
